---
- name: Upgrade all system packages
  community.general.pacman:
    upgrade: yes
    update_cache: true
  register: pacman_upgrade
  retries: 5
  until: pacman_upgrade is success

- name: Install common packages
  community.general.pacman:
    name:
      - ca-certificates
      - curl
      - iproute2 # net-tools available, but deprecated
      - iptables # in place of arptables & ebtables
      - iputils # in place of iputils-ping
      - ipvsadm
      - lvm2
      - nfs-utils # in place of nfs-common
      - open-iscsi
      - psmisc
      - smartmontools

      # - apt-transport-https # no equivalent
      # - software-properties-common # apt-add-repository, etc. no equivalent selected
      # - unattended-upgrades # no equivalent selected
    update_cache: false
  register: pacman_install_common
  retries: 5
  until: pacman_install_common is success

#- name: Check if Raspberry Pi
#  ansible.builtin.command: grep -q  "Raspberry Pi" /proc/cpuinfo
#  ignore_errors: true
#  register: is_raspberry

# Maybe check for arch rpi?
#- name: Install raspberry specific packages for Arch 21 or greater
#  ansible.builtin.apt:
#    name:
#      - linux-modules-extra-raspi
#    install_recommends: false
#    update_cache: true
#    cache_valid_time: 3600
#    autoclean: true
#    autoremove: true
#  ignore_errors: true
#  register: apt_install_raspberry
#  retries: 5
#  until: apt_install_raspberry is success
#  when: is_raspberry # and (ansible_lsb.major_release|int >= 21)

# TODO: systemd service to run pacman periodically? Install informant from AUR? How to get notified?

#- name: Copy 20auto-upgrades unattended-upgrades config
#  ansible.builtin.blockinfile:
#    path: /etc/apt/apt.conf.d/20auto-upgrades
#    mode: 0644
#    create: true
#    block: |
#      APT::Periodic::Update-Package-Lists "1";
#      APT::Periodic::Download-Upgradeable-Packages "1";
#      APT::Periodic::AutocleanInterval "7";
#      APT::Periodic::Unattended-Upgrade "1";
#
#- name: Copy 50unattended-upgrades unattended-upgrades config
#  ansible.builtin.blockinfile:
#    path: /etc/apt/apt.conf.d/50unattended-upgrades
#    mode: 0644
#    create: true
#    block: |
#      Unattended-Upgrade::Automatic-Reboot "false";
#      Unattended-Upgrade::Remove-Unused-Dependencies "true";
#      Unattended-Upgrade::Allowed-Origins {
#          "${distro_id} stable";
#          "${distro_id} ${distro_codename}-security";
#          "${distro_id} ${distro_codename}-updates";
#      };

#- name: Start unattended-upgrades service
#  ansible.builtin.systemd:
#    name: unattended-upgrades
#    enabled: true
#    state: started
#
#- name: Restart unattended-upgrades service
#  ansible.builtin.service:
#    name: unattended-upgrades.service
#    daemon_reload: true
#    enabled: true
#    state: restarted
