---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: upgrade
      community.general.pacman:
        upgrade: true
        update_cache: true
      register: pacman_upgrade
      retries: 5
      until: pacman_upgrade is success
