kind: Secret
ansible_user: ENC[AES256_GCM,data:Hd1n5I8FWQ==,iv:rNBtbnp21Kf+G8CDfRSeHa4ZXlPyRX+dDtV0gzlr0GA=,tag:VdxvMjacl2lgEyrRDjeurQ==,type:str]
ansible_private_key_file: ENC[AES256_GCM,data:CpMNlfix2BxrgqtHYA1r8W+2UH/sQQhz8TZEJ7x+ezBxzQ==,iv:Wfd3TDET1k2dy4+5cIU7r72A5xdqodDdBYZzzHTqpwY=,tag:K8v/0tmychhd6NwyNeO85w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:nf1IlTZ5A8s=,iv:Fg+V6OVMOObdLPXX3Lwkl1JrQMAu5qMZCKTv12Twc7s=,tag:yvWLhHqVhOu4qdiZ1Q5d1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t26g57yqgq9jhwqznl5mew2834r667gtjsfc0rqykr33qjetp3sc0ct7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Rk1JT3hLdEZOK0w5dFU4
            UXBYVDY4ay8rZUdsdnV6VkRHSlNvZC9EbkdRCkJoN0VrS2ZNZ2Y4YkxDMmNzWlBi
            WDhDRW1zRVErUXd3NitsNXdtZ1lJSDAKLS0tIFAwdlloRXRNUEZSbkpKTjhjNlk4
            T2xHK2tIcDl6ZmxLKzR5cEZYN1JNZHMKUEyitPd0swqXPattPW5w9cAD5Ui5sx7c
            CVJkAcrs/Lyp5KzrEO5l9hx4WJKRy7dxlkRQmvGoH52P1erJFrr9fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-27T18:13:40Z"
    mac: ENC[AES256_GCM,data:JsZP1dZGkngE2+KlxoAeD4Lrm0CXm54qLKgtLIDM2+/saUbntdrfpufUYJsVvfXPrESHMJfsIn4yVlAGbfrNNjJUvCm46Vs/F9qtGCLSOVnVkfZRya3nPrCojixQlnIfa+HsLQUnDmGoe7ekGZOzRfUGVugzZrKYQyl1bQiVOaM=,iv:4r7Pm8F9AI5p0sWQFslxv2sx4Z92jyKR223i4w2zV1g=,tag:oMm695cpZiEShIsVnQkjvA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
