kind: Secret
ansible_user: ENC[AES256_GCM,data:tLjOPWwuGw==,iv:4zzIw6Dgtgmzn/3phK3xnC6Vwk/40ZKnXV3RQJAZxGc=,tag:THd/e7RmrrZlrNY0Xho4JQ==,type:str]
ansible_private_key_file: ENC[AES256_GCM,data:Z/kDnglIvsYbf4Kj+qNWlUbMt9hZ51I0/sBbk0f4X4uiJA==,iv:IcvTXHWp8/5WX8HeW6eqo+0zdFkBdpWSMHR5QtnJ5sU=,tag:kDxEWXbO6GWjJu8YY2RtiQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:/2ZDDuNTv/o=,iv:nI4ArfcKnRuSGWI4Qi4uVgRKRajZb+9Qopl60X51Zu8=,tag:HjrGI4WhBwQSe+64v17rUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t26g57yqgq9jhwqznl5mew2834r667gtjsfc0rqykr33qjetp3sc0ct7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbVhGTk1ReE9KR3daeGFX
            TVBHUWRHMDF1a3VrM3dNdDJGamcrOHZxWFJjCkhuWG50ZnJRdk4rWndJSXJBRVpZ
            Z2FKSlZXZ3BPK2hrcTlpRW40eHdRL1kKLS0tIGNIbWhKMURwYjlZeGFPVmZLYUFF
            UC9ieFFCd0Nsc1dXNWU5VUlRYmQ2YkkK1Lp3784g2tn7Ai98rZMewokkw0Hao2DG
            migrTMNAM7GvYz4MPfnYA39ij3xJvQZYVdvFvXoAsN6BN2RnawsVDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-27T17:27:40Z"
    mac: ENC[AES256_GCM,data:JJZ4tJmS4lgSh9+Jc0t+snrbZJOUG3SVkPKSX6lsMgdlDOnlm7L1z7f8X2yRmCRBq7aMUaIR7RggcVnxJ840DEpOM31mFmtQ2ST/LfKZYuDuNPA/HwwtuVyZW4pXYTmQDCd/5l6f5GmgzIVfcrCnCueiubKXwcEAtxwCDi9sm4U=,iv:RUYF+XFe2tYfbUPwdRvGC6weq+Qu8klItlubVuCzMuE=,tag:MIT2Tpsi1x3j5RXCCoxQJg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
