# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:u1zwZMlQf1jsWhk8cJ8j1RCQ,iv:Fa9rlsCAQd2FLTfdfWDakL8cNhwMmqXH5wr20LsBC/8=,tag:oYaiHG2ZT02RtNIDXBHI5A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JuDtgKe9LpPqmxjSOv2bitKgpPydigqB,iv:PeZoEjJ/3hd60LnaDDtVgbxZEf+ZPJwkRQSau0XmsZs=,tag:xWFs+7KizaeCAjWEyC2d3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t26g57yqgq9jhwqznl5mew2834r667gtjsfc0rqykr33qjetp3sc0ct7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbE1ZN09PbWVpL3J1M240
            Tk9SZDhYZDYzanZTQ05YZTNrU3N6Q1JVL1hNClBqQnQ4V1RiVnQvSXUyUmhxNG02
            SzM4R3E3NEtkaDdTSWxFSSs5N3c0ZjAKLS0tIGdrMEdwTjdTVXptYjVtcmVkbDBK
            UmhybVBkVDkyRUUxRXlydWNEdTJNV0kK4L2nZjQWTV+ARgd6ZPXUlK8zuql7dZgE
            KOoMtCsu6fhXzqIRM8fFMfkquY6fxYtit1qxD1bv8Z7014XffuOmyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-27T17:27:40Z"
    mac: ENC[AES256_GCM,data:Cvrphxiqz9DtwChlsOdYbxqiMaXwjZOV+PBW3y43mhbDwLc6AsocU1S5l4ZEDk1JK1+uiI/wi5qVURxtjylqFjTnJsoaPtOfdt00S3AzNtZghUV/tA9RZA2NsNo7pIqFCfooYDitS/TVxHHEKr7Pxvv6ZSf3VxoDCN3JFfLVNik=,iv:MSJoy/v2TZXhck22tO/Ftv+s6UQv+q7/bmM3vu5dc0k=,tag:heY7PrvnFWLlzpZh4vwaIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
