# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XzFf2mHqKtQr+JFfkUMBv3y5,iv:9DqYZKvJrexyiZA1poARH1skgDyBt3Ia2HGd/IGoLas=,tag:i04sn6wTqKp3+0jr47MCzQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qub/TyVG8RgPrxkrLHCCt/K9nDevNnTx,iv:0MWdwZgWtIaiTbj7Tj3XhUsUkZVrbLX5mDhE4u6BCT4=,tag:dWeGe+Ty36zIpCTv63xQqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t26g57yqgq9jhwqznl5mew2834r667gtjsfc0rqykr33qjetp3sc0ct7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNXp5T1p0KzcxS212TVZx
            T3FJaW96cENlSTFsVytJRkRRSHNDQUtqMkY0CjVzV3Vpc0Y4MEhpa1QvUWRQK2sy
            RnZxam5xNnBPMzBrY3Z5UE1IUnpRN00KLS0tIG0xaGc4UW1nQzA0Z0JWa2tjNk1m
            NEdaYis0RnJMMTFmR0d0cDdRZFM4TU0KQt+3i3mpjtViyWkMgQmqodE/t2sJBQVp
            O6NL2xovasWFbp5r50Eu3hIYaKkfRj+NxYzQAfYLmBU4xMaFH8RHDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-27T18:13:40Z"
    mac: ENC[AES256_GCM,data:YGc9JUhuuxJzl+U/dNUERsoI/FISmcVPrXro2eIrikR7kj/5zyOzyonnlgW+AlEUN8Hs5fn8qzHJ6fLJ9nlV/SO9Jp9jMnoAP5hXHHHXftiPzGbjvf2n4Q1LOLycBvELEmLkN05xtf3PvNIUrw3I3mY0u+4FVLV58onAUvFA/Ds=,iv:QVAnMUzn6H3ZlLEW8v4By05GnA0+ba0D5qctIQjTODQ=,tag:Vn23JfLCC+4ivHdPqBS9BA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
